export const pelis = [
    {
        "id": 1,
        "name": "Un lugar en silencio II",
        "first_appearance": "Un lugar en silencio II",
        "image": "https://archivos-cms.cinecolombia.com/images/_aliases/poster_card/4/5/7/8/18754-1-esl-CO/2-Cineco-poster-480x670px.png",
        "informacion" : "La familia Abbott ahora se enfrenta a los terrores del mundo exterior. Forzados a aventurarse en lo desconocido, se dan cuenta de que las criaturas que cazan por el sonido no son las únicas amenazas que acechan más allá del camino de arena.",
        "redirect" : "./info/Un_lugar_en_silencio.html"
      },
      {
        "id": 2,
        "name": "Eternos compañeros",
        "first_appearance": "Eternos compañeros",
        "image": "https://archivos-cms.cinecolombia.com/images/_aliases/poster_card/0/7/3/0/20370-1-esl-CO/Poster%201080%20alto%20x%201600%20.jpg",
        "informacion" : "Un labrador llamado Little Q, con una curiosa marca de nacimiento, se está entrenando para convertirse en un perro guía para ciegos. Cuando se completa su formación, lo envían a ayudar a un famoso chef recientemente ciego, Lee Bo Ting.",
        "redirect" : "./info/Eternos_compañeros.html",
      },
      {
        "id": 3,
        "name": "Justicia implacable",
        "first_appearance": "Justicia implacable",
        "image": "https://archivos-cms.cinecolombia.com/images/_aliases/poster_card/7/4/4/9/19447-1-esl-CO/Poster_480x%20670.png",
        "informacion" : "Harry es el misterioso tipo que se incorpora como guardia de seguridad en una compañía de blindados. Durante un intento de atraco a su camión, sorprende a sus compañeros mostrando habilidades de un soldado profesional, dejando al resto preguntándose quién es realmente y de dónde viene.",
        "redirect" : "./info/Justicia_implacable.html",
      },
      {
        "id": 4,
        "name": "El olvido que seremos",
        "first_appearance": "El olvido que seremos",
        "image": "https://archivos-cms.cinecolombia.com/images/_aliases/poster_card/8/1/3/6/16318-12-esl-CO/EOQS_poster_300x450.jpg",
        "informacion" : "La historia del padre de un escritor colombiano. Su padre fue un profesor universitario que promovió la tolerancia y los derechos humanos en su país. El escritor expone sus sentimientos relacionados con su adorable padre.",
        "redirect" : "./info/El_olvido_que_seremos.html",
      },
      {
        "id": 5,
        "name": "Free guy",
        "first_appearance": "Free guy",
        "image": "https://archivos-cms.cinecolombia.com/images/_aliases/poster_card/0/5/8/3/13850-18-esl-CO/FREE%20GUY%20TOMANDO%20EL%20CONTROL%20P%C3%93STER.jpg",
        "informacion" : "Un cajero de un banco descubre que en realidad es un personaje sin papel dentro de un brutal videojuego de mundo interactivo.",
        "redirect" : "./info/Free_guy.html",
      },
      {
        "id": 6,
        "name": "La casa oscura",
        "first_appearance": "La casa oscura",
        "image": "https://archivos-cms.cinecolombia.com/images/_aliases/poster_card/8/3/7/0/20738-1-esl-CO/Poster_480x670.png",
        "informacion" : "Mientras intenta superar la inesperada muerte de su marido, Beth se queda sola en una casa cerca de un lago. Aunque hace todo lo posible por no perder la cordura, las perturbadoras visiones de una presencia comienzan a ser más frecuentes.",
        "redirect" : "./info/La_casa_oscura.html",
      },
      {
        "id": 7,
        "name": "Reminiscencia",
        "first_appearance": "Reminiscencia",
        "image": "https://archivos-cms.cinecolombia.com/images/_aliases/poster_card/3/5/6/9/19653-1-esl-CO/LM_LAS_REM_VERT_MAIN_2764x4096_INTL.jpg",
        "informacion" : "Tony Stark (Robert Downey Jr., 'Chaplin'), dueño de Industrias Stark, inventor consagrado, vendedor de armas y playboy multimillonario, es secuestrado en Afganistán después de una demostración armamentística para el Ejército de los Estados Unidos. Forzado por sus captores a fabricar un arma temible, acaba construyendo en secreto una armadura de alta tecnología revolucionaria que usa para escaparse.",
        "redirect" : "./info/Reminiscencia.html",
      },
      {
        "id": 8,
        "name": "Asesinos anónimos",
        "first_appearance": "Asesinos anónimos",
        "image": "https://archivos-cms.cinecolombia.com/images/_aliases/poster_card/2/8/2/9/19282-1-esl-CO/AsesinosAnonimos_DGT_COL%20(1).jpg",
        "informacion" : "La tensión es insoportable dentro de Asesinos Anónimos, un grupo de apoyo, cuando todos intentan descubrir quién está detrás de un ataque contra un senador.",
        "redirect" : "./info/Asesinos_anonimos.html",
      },
      {
        "id": 9,
        "name": "El mensajero",
        "first_appearance": "El mensajero",
        "image": "https://archivos-cms.cinecolombia.com/images/_aliases/poster_card/7/4/5/8/18547-2-esl-CO/2_poster_480x670.png",
        "informacion" : "La tensión es insoportable dentro de Asesinos Anónimos, un grupo de apoyo, cuando todos intentan descubrir quién está detrás de un ataque contra un senador.",
        "redirect" : "./info/El_mensajero.html",
      }
    ]